### ISSUE TITLE
Lack of Piece CID in manifest.csv when generating car files

### ISSUE THREAD

**Issue by GuohaoMa** [filedrive-team/go-graphsplit#11]
An import piece of information about Piece CID is missing in latest release v0.3.0.  The absence of piece CID will cause the failure of sending filecoin offline deals and hereby weaken the generalization of go-graphsplit. Is it possible to record piece CID and add it into manifest.csv in the coming release？Expecting more details about the CID information.

**Comment by beeleelee** [comment]
Piece CID generation haven't been supported by go-graphsplit yet. Fortunately, we are planning to add more features to better support the data pre-processing for offline deals. If everything goes ok, will landing these features to the next release.

**Comment by flyworker** [comment]
Do you have an estimated time of release data?

**Comment by laurarenpanda** [comment]
> Do you have an estimated time of release data?

@flyworker
Hi, Charles. The new version will be released before next Monday. If everything goes well, this feature will be available on this Friday. And we will update branch first, so you can use this feature before the formal version release.

**Comment by flyworker** [comment]
Great, we will wait for you guys completed then integrate it to Filswan service.
Thanks

**Comment by beeleelee** [comment]
Has integrated PieceCID calculation feature into the chunk process, set --calc-commp=true to using this feature.

**Comment by beeleelee** [comment]
Be careful, a lot of cpu and memory would be consumed if slice size is very large.
