### ISSUE TITLE
An error occurs when restore

### ISSUE THREAD

**Issue by ericxiao0417** [filedrive-team/go-graphsplit#13]
I chunk a xlsx file within absolute path successfully. But when I restore it, an error occurs. Though the restore process is completed, but the xlsx file can't be opened.
<img width="1234" alt="WX20210604-105802@2x" src="https://user-images.githubusercontent.com/19838051/120740385-ae14e980-c525-11eb-86c0-869cb10096e0.png">

**Comment by qianhh** [comment]
Thank you for your feedback. The problem may be related to the -- parent-path parameter in chunk. I will fix it soon. If you're in a hurry, you can change the -- parent-path to a directory. Good luck.
