### ISSUE TITLE
Would like a CSV report on what's inside each CAR

### ISSUE THREAD

**Issue by kernelogic** [filedrive-team/go-graphsplit#16]
Hello, it would be great to have the CSV include what's inside each CSV, or a separate CSV contain such information.

**Comment by laurarenpanda** [comment]
> Hello, it would be great to have the CSV include what's inside each CSV, or a separate CSV contain such information.

Thanks, @kernelogic. That's a good idea! We will add this function in next release.

**Comment by beeleelee** [comment]
Would like to add a field `detail` to the manifest.csv in the form of JSON string to record the inner file structure.
