### ISSUE TITLE
A new way to record correspondence between Data Cids and fragment files

### ISSUE THREAD

**Issue by laurarenpanda** [filedrive-team/go-graphsplit#6]
Currently, after using Go-graphsplit to slice dataset, we use manifest.csv to record the correspondence between Data Cids and fragment files. 
However, if users wants to save Data Cids and fragment files’ name to the database, they need to write a script to process manifest.csv. 
Expectation: make generating manifest.csv optional, and provide users a way to choose how to save Data Cids and information of fragment files.

**Comment by beeleelee** [comment]
Make generating manifest.csv optinal is ok.
The best way for users to choose alternative ways to save Data Cids and information of fragment files is using graphsplit as a library. We would export an callback function to let users handle the data recording staff.
